watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: 'komorebic start --whkd'
  stop_command: 'komorebic stop --whkd'
  reload_command: 'komorebic stop --whkd && komorebic start --whkd'
bars:
  primary-bar:
    enabled: true
    screens: ['*']
    class_name: 'yasb-bar'
    alignment:
      position: 'top'
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: '100%'
      height: 22
    padding:
      top: 2
      left: 4
      bottom: 0
      right: 4
    widgets:
      left: ['win_button', 'taskbar', 'active_window']
      center: []
      right: ['traffic', 'pomodoro', 'volume', 'clock', 'power_menu']
widgets:
  language:
    type: 'yasb.language.LanguageWidget'
    options:
      label: "<span>\uf11c</span>{lang[country_code]}"
      update_interval: 5
      callbacks:
        on_left: 'do_nothing'
        on_middle: 'do_nothing'
        on_right: 'do_nothing'
  active_window:
    type: 'yasb.active_window.ActiveWindowWidget'
    options:
      label: '{win[title]}'
      label_alt:
        "[class_name='{win[class_name]}' exe='{win[process][name]}'
        hwnd={win[hwnd]}]"
      label_no_window: 'Hey Man! Have a good day...'
      label_icon: false
      label_icon_size: 14
      max_length: 100
      max_length_ellipsis: '...'
      monitor_exclusive: true
      callbacks:
        on_left: 'do_nothing'
        on_middle: 'do_nothing'
        on_right: 'do_nothing'
  clock:
    type: 'yasb.clock.ClockWidget'
    options:
      label: "<span>\udb83\ude17</span>{%a  %b %d  %I:%M %p}"
      label_alt: "<span>\udb83\ude17</span>{%A, %d %B %Y %I:%M %p}"
      timezones: ['Asia/Dhaka']
  komorebi_workspaces:
    type: 'komorebi.workspaces.WorkspaceWidget'
    options:
      label_offline: "\u26a1 Offline"
      label_workspace_btn: ''
      label_workspace_active_btn: ''
      label_workspace_populated_btn: ''
      label_default_name: '{index}'
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: false
      animation: true
  glazewm_workspaces:
    type: 'glazewm.workspaces.GlazewmWorkspacesWidget'
    options:
      # Offline behavior (matching komorebi's label_offline and hide_if_offline)
      offline_label: 'GlazeWM Offline'
      hide_if_offline: true

      # Workspace display labels (matching komorebi's label_workspace_btn and label_workspace_active_btn)
      populated_label: ''
      empty_label: ''
      active_populated_label: ''
      active_empty_label: ''

      # Workspace management (matching komorebi's hide_empty_workspaces)
      hide_empty_workspaces: false

      # Server connection
      glazewm_server_uri: 'ws://localhost:6123'

      # Additional GlazeWM-specific options (keeping defaults)
      enable_scroll_switching: true
      reverse_scroll_direction: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

  glazewm_tiling_direction:
    type: 'glazewm.tiling_direction.GlazewmTilingDirectionWidget'
    options:
      horizontal_label: "\uf07e"
      vertical_label: "\uf07d"
      btn_shadow:
        enabled: true
        color: 'black'
        radius: 0
        offset: [2, 2]

  pomodoro:
    type: 'yasb.pomodoro.PomodoroWidget'
    options:
      label: '<span>{icon}</span> {remaining}'
      label_alt: '<span>{icon}</span> {session}/{total_sessions} - {status}'
      work_duration: 25
      break_duration: 5
      long_break_duration: 15
      long_break_interval: 4
      auto_start_breaks: true
      auto_start_work: true
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 8
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      container_padding:
        top: 0
        left: 1
        bottom: 0
        right: 1
      menu:
        blur: true
        round_corners: true
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'right'
        direction: 'down'
        offset_top: 6
        offset_left: 0
        circle_background_color: '#09ffffff'
        circle_work_progress_color: '#88c0d0'
        circle_break_progress_color: '#a3be8c'
        circle_thickness: 10
        circle_size: 160
      callbacks:
        on_left: 'toggle_menu'
        on_middle: 'reset_timer'
        on_right: 'toggle_label'
      label_shadow:
        enabled: true
        color: 'black'
        radius: 2
        offset: [1, 1]
  volume:
    type: 'yasb.volume.VolumeWidget'
    options:
      label: '<span>{icon}</span> {level}'
      label_alt: '{volume}'
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_right: 'exec cmd.exe /c start ms-settings:sound'
  power_menu:
    type: 'yasb.power_menu.PowerMenuWidget'
    options:
      label: "<span>\uf011</span>"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200 # Milisecond
      button_row: 5 # Number of buttons in row, min 1 max 5
      buttons:
        shutdown: ["\uf011", 'Shut Down']
        restart: ["\uead2", 'Restart']
        signout: ["\udb80\udf43", 'Sign out']
        hibernate: ["\uf28e", 'Hibernate']
        sleep: ["\u23fe", 'Sleep']
        cancel: ['', 'Cancel']
  taskbar:
    type: 'yasb.taskbar.TaskbarWidget'
    options:
      animation:
        enabled: true
      icon_size: 14
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

  win_button:
    type: 'yasb.custom.CustomWidget'
    options:
      label: "<span>\udb80\udf5c</span>"
      label_alt: "<span>\udb80\udf5c</span>"
      class_name: 'win-btn'
      callbacks:
        on_left: 'exec start_menu'
  traffic:
    type: 'yasb.traffic.TrafficWidget'
    options:
      label:
        "<span>\udb82\udcfa</span> \uea9a{download_speed} \ueaa1{upload_speed}"
      label_alt:
        "<span>\udb82\udcfa</span> Download {download_speed} | Upload
        {upload_speed}"
      update_interval: 1000
      callbacks:
        on_left: 'do_nothing'
        on_right: 'exec cmd /c Taskmgr'
